config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :restaurants do
    resources :reviews
  end
  root 'restaurants#index'

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base

  has_many :reviews
  has_many :users, through: :reviews
end

app/models/review.rb
class Review < ActiveRecord::Base
  validates :point, numericality: {
            only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 5
          }

  belongs_to :restaurant
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :reviews
  has_many :restaurants, through: :reviews
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:account_update) << :name
  end

end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  # GET /restaurants
  # GET /restaurants.json
  def index
    @restaurants = Restaurant.all

    @max = 0
    @max_restaurant
    @restaurants.each do |restaurant|
      num = 0
      sum = 0
      restaurant.reviews.each do |review|
        sum += review.point
        num += 1
      end
      average = sum.to_f/num

      if average >= @max
        @max = average
        @max_restaurant = restaurant
      end
    end
  end

  # GET /restaurants/1
  # GET /restaurants/1.json
  def show
    @num = 0
    @sum = 0
    # @restaurant = Restaurant.find(params[:id])
    @restaurant.reviews.each do |review|
      @sum += review.point
      @num += 1
    end
    @average = @sum.to_f/@num
  end

  # GET /restaurants/new
  def new
    @restaurant = Restaurant.new
  end

  # GET /restaurants/1/edit
  def edit
  end

  # POST /restaurants
  # POST /restaurants.json
  def create
    @restaurant = Restaurant.new(restaurant_params)

    respond_to do |format|
      if @restaurant.save
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully created.' }
        format.json { render :show, status: :created, location: @restaurant }
      else
        format.html { render :new }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /restaurants/1
  # PATCH/PUT /restaurants/1.json
  def update
    respond_to do |format|
      if @restaurant.update(restaurant_params)
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully updated.' }
        format.json { render :show, status: :ok, location: @restaurant }
      else
        format.html { render :edit }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurants/1
  # DELETE /restaurants/1.json
  def destroy
    @restaurant.destroy
    respond_to do |format|
      format.html { redirect_to restaurants_url, notice: 'Restaurant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def restaurant_params
      params.require(:restaurant).permit(:name, :telephone, :address, :home_page, :image, :area)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def edit
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.find(params[:id])
  end

  def create
    @review = Review.new(
      restaurant_id: params[:restaurant_id],
      user_id: current_user.id,
      body: review_params["body"],
      point: review_params["point"]
    )
    if @review.save
      redirect_to restaurant_url(@review.restaurant)
    else
      render :new
    end
  end

  def update
    @review = Review.find(params[:id])
    if @review.update(
      restaurant_id: params[:restaurant_id],
      user_id: current_user.id,
      body: review_params["body"],
      point: review_params["point"]
    )
      redirect_to @review.restaurant
    else
      render :new
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.delete
    redirect_to @review.restaurant
  end

  private

  def review_params
    params.require(:review).permit(:body, :point)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-menu">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/restaurants">スパル食べログ</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="navbar-collapse-menu">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <p class="navbar-text">
            <%= current_user.name %>さんようこそ！
          </p>
          <li><%= link_to 'お店を登録', new_restaurant_path %></li>
          <!-- <li><a href="#">設定変更</a></li> -->
          <li><%= link_to '設定変更', edit_user_registration_path %></li>
          <!-- <li><a href="#">ログアウト</a></li> -->
          <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
        <% else %>
          <!-- <li><a href="#">新規登録</a></li> -->
          <li><%= link_to '新規登録', new_user_registration_path %></li>
          <!-- <li><a href="#">ログイン</a></li> -->
          <li><%= link_to 'ログイン', new_user_session_path %></li>
          <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tabelog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">

  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap-theme.min.css">

  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>

</head>
<body>
<%= render partial: 'layouts/header' %>

<div class="container">
  <% if notice.present? %>
    <div class="alert alert-dismissable alert-success">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <p><%= notice %></p>
    </div>
  <% end %>
  <% if alert.present? %>
    <div class="alert alert-dismissable alert-danger">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <p><%= alert %></p>
    </div>
  <% end %>
  <%= yield %>
</div>
</body>
</html>

app/views/restaurants/_form.html.erb
<%= form_for(@restaurant) do |f| %>
  <% if @restaurant.errors.any? %>
    <div class="alert alert-danger">
      <p><b><%= @restaurant.errors.count %>件のエラーがあります</b></p>

      <ul>
      <% @restaurant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
  <%= f.label :name, "名前" %>
  <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
  <%= f.label :telephone, "電話番号" %>
  <%= f.text_field :telephone, class: "form-control" %>
  </div>

  <div class="form-group">
  <%= f.label :area, "エリア" %>
  <%= f.text_field :area, class: "form-control" %>
  </div>

  <div class="form-group">
  <%= f.label :address, "住所" %>
  <%= f.text_field :address, class: "form-control" %>
  </div>

  <div class="form-group">
  <%= f.label :home_page, "ホームページ" %>
  <%= f.text_field :home_page, class: "form-control" %>
  </div>

  <div class="form-group">
  <%= f.label :image, "画像" %>
  <%= f.text_field :image, class: "form-control" %>
  </div>

  <%= f.submit '登録する', class: "btn btn-primary" %>

<% end %>

app/views/restaurants/edit.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1>レストラン情報の編集</h1>
    <%= render 'form' %>
    <br>
    <button type="button" class="btn btn-default btn-sm" data-toggle="modal" data-target="#delete-restaurant">レストラン情報を削除する</button>
  </div>
</div>

<!-- 下記のモーダルは通常は隠れているので、どこに書いてもＯＫ -->
<div class="modal fade" id="delete-restaurant">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">レストラン情報の削除</h4>
      </div>
      <div class="modal-body">
        <p><%= @restaurant.name %>を削除しますか？</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">キャンセル</button>
        <%= link_to '削除する', @restaurant, method: :delete, class: "btn btn-danger" %>
      </div>
    </div>
  </div>
</div>

<%= link_to 'Show', @restaurant %> |
<%= link_to 'Back', restaurants_path %>

app/views/restaurants/index.html.erb
<div class="row">
  <div class="col-md-12">
    <% @restaurants.reverse_each do |restaurant| %>
    <div class="col-sm-6 col-md-4">
      <div class="thumbnail" >
        <h4 class="text-center"><span class="label label-info"><%= restaurant.area %></span></h4>
          <img src=<%= restaurant.image %> class="img-responsive">
            <div class="caption">
              <div class="row">
                <div class="col-md-12 col-xs-12">
                  <h3><%= restaurant.name %></h3>
                </div>
            </div>
            <p><span class="glyphicon glyphicon-earphone"></span> <%= restaurant.telephone %></p>
            <div class="row">
              <div class="col-md-4">
                <a href="restaurants/<%= restaurant.id %>/" class="btn active btn-info btn-product"><span class="glyphicon glyphicon-plus"></span> 詳細</a>
              </div>
              <div class="col-md-4">
                <a href="restaurants/<%= restaurant.id %>/edit/" class="btn active btn-warning btn-product"><span class="glyphicon glyphicon-wrench"></span> 編集</a></div>
              <div class="col-md-4">
                <a href="restaurants/<%= restaurant.id %>/" data-method="delete" class="btn active btn-danger btn-product"><span class="glyphicon glyphicon-trash"></span> 削除</a></div>
            </div>
            <p> </p>
          </div>
        </div>
    </div>
    <% end %>
  </div>
</div>

<hr>

<h2>一番評価の高いお店</h2>
    <div class="col-sm-6 col-md-4">
      <div class="thumbnail" >
        <h4 class="text-center"><span class="label label-info"><%= @max_restaurant.area %></span></h4>
          <img src=<%= @max_restaurant.image %> class="img-responsive">
            <div class="caption">
              <div class="row">
                <div class="col-md-12 col-xs-12">
                  <h3><%= @max_restaurant.name %></h3>
                </div>
            </div>
            <p><span class="glyphicon glyphicon-earphone"></span> <%= @max_restaurant.telephone %></p>
            <span class="testimonials-post">評価：<%= @max %>点</span>
            <div class="row">
              <div class="col-md-4">
                <a href="restaurants/<%= @max_restaurant.id %>/" class="btn active btn-info btn-product"><span class="glyphicon glyphicon-plus"></span> 詳細</a>
              </div>
              <div class="col-md-4">
                <a href="restaurants/<%= @max_restaurant.id %>/edit/" class="btn active btn-warning btn-product"><span class="glyphicon glyphicon-wrench"></span> 編集</a></div>
              <div class="col-md-4">
                <a href="restaurants/<%= @max_restaurant.id %>/" data-method="delete" class="btn active btn-danger btn-product"><span class="glyphicon glyphicon-trash"></span> 削除</a></div>
            </div>
            <p> </p>
          </div>
        </div>
    </div>

app/views/restaurants/new.html.erb
<h1>New Restaurant</h1>

<%= render 'form' %>

<%= link_to 'Back', restaurants_path %>

app/views/restaurants/show.html.erb
<div class="row">
  <div class="col-md-6">
    <div class="col-sm-10 col-md-10">
      <div class="thumbnail" >
        <h4 class="text-center"><span class="label label-info"><%= @restaurant.area %></span></h4>
          <img src=<%= @restaurant.image %> class="img-responsive">
            <div class="caption">
              <div class="row">
                <div class="col-md-12 col-xs-12">
                  <h3><%= @restaurant.name %></h3>
                </div>
            </div>
            <p><span class="glyphicon glyphicon-earphone"></span> <%= @restaurant.telephone %></p>
            <p>住所：<%= @restaurant.address %></p>
            <p>ホームページ：<%= @restaurant.home_page %></p>
            <p>平均点：<%= @average %></p>
            <div class="row">
              <div class="col-md-6">
                <a href="edit/" class="btn active btn-warning btn-product"><span class="glyphicon glyphicon-wrench"></span> 編集</a></div>
              <div class="col-md-6">
                <a href="" data-method="delete" class="btn active btn-danger btn-product"><span class="glyphicon glyphicon-trash"></span> 削除</a></div>
            </div>
            <p> </p>
          </div>
        </div>
    </div>
  </div>
  <div class="col-md-6">
  <% @restaurant.reviews.each do |review| %>
    <div class="row">
      <div class="col-md-10 col-md-offset-1">
        <div class="testimonials">
          <div class="active item">
            <blockquote><p><%= simple_format(review.body) %></p></blockquote>
            <div class="carousel-info">
              <img alt="" src="https://ssl.gstatic.com/accounts/ui/avatar_2x.png" class="pull-left">
                <div class="pull-left">
                  <span class="testimonials-name"><%= review.user.name %>さん</span>
                  <span class="testimonials-post">評価：<%= review.point %>点</span>
                  <p><%= review.created_at.strftime('%Y/%m/%d %H:%M') %></p>
                </div>
                <div class="pull-right">
                  <% if review.user.id == current_user.id %>
                  <%= link_to '編集', edit_restaurant_review_path(@restaurant, review), class: "btn active btn-warning btn-product" %>
                  <%= link_to '削除', restaurant_review_path(@restaurant, review), method: :delete, class: "btn active btn-danger btn-product" %>
                  <% end %>
                </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <hr>
  <% end %>
  </div>
</div>

<%= link_to 'レビューを書く', new_restaurant_review_path(@restaurant), class: "btn-default"%>
<%= link_to '編集', edit_restaurant_path(@restaurant) %> |
<%= link_to '戻る', restaurants_path %>

app/views/review/_form.html.erb
<%= form_for([@restaurant, @review]) do |f| %>
  <% if @review.errors.any? %>
    <div class="alert alert-danger">
      <p><b><%= @review.errors.count %>件のエラーがあります</b></p>

      <ul>
      <% @review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :body, "レビュー" %>
    <%= f.text_field :body, class: "form-control" %>
  </div>

  <%= f.submit '登録する', class: "btn btn-primary" %>

<% end %>

app/views/review/new.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1>ニューレビュー登録</h1>
    <ul>
      <li>店名：<%= @restaurant.name %></li>
      <li>TEL：<%= @restaurant.telephone %></li>
      <li>住所：<%= @restaurant.address %></li>
      <li>ホームページ：<%= @restaurant.home_page %></li>
    </ul>

    <hr>
    <%= render 'form' %>
  </div>
</div>

app/views/reviews/_form.html.erb
<%= form_for([@restaurant, @review]) do |f| %>
  <% if @review.errors.any? %>
    <div class="alert alert-danger">
      <p><b><%= @review.errors.count %>件のエラーがあります</b></p>

      <ul>
      <% @review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :body, "レビュー" %>
    <%= f.text_field :body, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :point, "点数" %>
    <%= f.number_field :point, class: "form-control" %>
  </div>

  <%= f.submit '登録する', class: "btn btn-primary" %>

<% end %>

app/views/reviews/edit.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1>レビューの編集</h1>
    <%= render 'form' %>
    <br>
  </div>
</div>

app/views/reviews/new.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1>ニューレビュー登録</h1>
    <ul>
      <li>店名：<%= @restaurant.name %></li>
      <li>TEL：<%= @restaurant.telephone %></li>
      <li>住所：<%= @restaurant.address %></li>
      <li>ホームページ：<a href=<%= @restaurant.home_page %>><%= @restaurant.home_page %></a></li>
    </ul>

    <hr>
    <%= render 'form' %>
  </div>
</div>